"use client";

import { motion } from "motion/react";
import Link from "next/link";
import Image from "next/image";
import PageHero from "@/components/PageHero";
import ServicesEcosystem from "@/components/ServicesEcosystem";

const EASE = [0.22, 1, 0.36, 1] as [number, number, number, number];

const fadeUp = {
  hidden: { opacity: 0, y: 32 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease: EASE } },
};

const stagger = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.1 } },
};

const Arrow = () => (
  <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
    <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3" />
  </svg>
);

const SERVICES = [
  {
    num: "01",
    title: "Security Information and Event Management (SIEM)",
    desc: "Our SIEM solutions provide real-time analysis of security alerts generated by applications and network hardware, ensuring timely detection and response to potential threats.",
    href: "/siem-as-a-service",
    image: "https://nextcloud.illumiasolutions.com/public.php/dav/files/7CtcpxZJFnQbEZi",
    imageAlt: "SIEM analytics dashboard",
  },
  {
    num: "02",
    title: "Security Orchestration, Automation, and Response (SOAR)",
    desc: "SOAR solutions automate security operations, freeing up your IT team to focus on strategic tasks while ensuring rapid and effective incident response.",
    href: "/soar",
    image: "https://nextcloud.illumiasolutions.com/public.php/dav/files/Enx2Nx5t3QN7PJy",
    imageAlt: "Security automation",
  },
  {
    num: "03",
    title: "Endpoint Detection and Response (EDR)",
    desc: "Our EDR solutions offer comprehensive visibility into endpoint activities, enabling proactive threat detection and response to mitigate potential risks.",
    href: "/edr-solution",
  },
  {
    num: "04",
    title: "Vulnerability Management",
    desc: "We provide robust vulnerability management solutions that identify, evaluate, and remediate security weaknesses, ensuring your systems remain secure.",
    href: "/vulnerability-management",
  },
  {
    num: "05",
    title: "Governance, Risk, and Compliance (GRC)",
    desc: "Our GRC solutions streamline the process of managing regulatory compliance, enterprise risk, and corporate governance, helping you stay compliant and minimise risks.",
    href: "/governance-risk-compliance",
  },
  {
    num: "06",
    title: "Privileged Access Management (PAM)",
    desc: "PAM solutions safeguard your critical assets by controlling and monitoring privileged access, ensuring only authorised users can access sensitive information.",
    href: "/pam-as-a-service",
  },
  {
    num: "07",
    title: "Honeypot Solutions",
    desc: "Deploying honeypots allows us to detect, deflect, and analyse attempts at unauthorised use of information systems, providing valuable insights into potential threats.",
    href: "/honeypot-solution",
    image: "https://nextcloud.illumiasolutions.com/public.php/dav/files/24pgQ3pHZkCZmE9",
    imageAlt: "Cybersecurity honeypot",
  },
  {
    num: "08",
    title: "Monitoring and Analytical Systems",
    desc: "Our advanced monitoring and analytical systems ensure continuous oversight of your IT environment, enabling early detection of anomalies and informed decision-making.",
    href: "/monitoring-analytics",
  },
];

export default function CybersecuritySolutionsPage() {
  return (
    <>
      {/* ─── Hero ─────────────────────────────────────────────────────────── */}
      <PageHero
        badge="Cybersecurity Solutions"
        title={
          <>
            Cybersecurity{" "}
            <span className="italic font-normal text-[#b31c33]">Solutions.</span>
          </>
        }
        description="Cybersecurity is at the core of our services at Illumia Solutions. We offer a range of solutions to protect your business from evolving cyber threats."
        primaryCta={{ label: "Explore Solutions", href: "#solutions" }}
        secondaryCta={{ label: "Contact Us", href: "/contact#contact-form" }}
        imageSrc="https://nextcloud.illumiasolutions.com/public.php/dav/files/24pgQ3pHZkCZmE9"
        imageAlt="Cybersecurity Solutions — Illumia Solutions"
      />

      {/* ─── Solutions Grid ───────────────────────────────────────────────── */}
      <section id="solutions" className="py-20 px-6 md:px-12 bg-[#f6f3f2] scroll-mt-20">
        <div className="max-w-screen-2xl mx-auto">
          <motion.div
            variants={stagger}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-60px" }}
            className="mb-14"
          >
            <motion.span variants={fadeUp} className="font-body text-xs tracking-[0.25em] uppercase text-[#b31c33] font-bold block mb-4">
              Our Solutions
            </motion.span>
            <motion.h2 variants={fadeUp} className="font-headline text-4xl md:text-5xl text-stone-900">
              Cybersecurity Solutions
            </motion.h2>
          </motion.div>

          {/* Row 1: SIEM (wide image overlay) + SOAR (white card with image) */}
          <motion.div
            variants={stagger}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-60px" }}
            className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-4"
          >
            <motion.div variants={fadeUp} className="lg:col-span-2 h-full">
              <Link
                href={SERVICES[0].href}
                className="group relative block rounded-2xl overflow-hidden min-h-[360px] h-full"
              >
                <Image
                  src={SERVICES[0].image!}
                  alt={SERVICES[0].imageAlt!}
                  fill
                  className="object-cover group-hover:scale-105 transition-transform duration-700"
                />
                <div className="absolute inset-0 bg-[#1c1b1b]/62 group-hover:bg-[#1c1b1b]/52 transition-colors" />
                <div className="absolute inset-0 p-10 flex flex-col justify-between">
                  <span className="font-body text-xs tracking-[0.3em] uppercase text-white/60 font-bold">{SERVICES[0].num}</span>
                  <div>
                    <h3 className="font-headline text-3xl text-white mb-3">{SERVICES[0].title}</h3>
                    <p className="text-white/70 text-sm font-body leading-relaxed mb-6 max-w-md">{SERVICES[0].desc}</p>
                    <span className="font-body font-semibold text-xs inline-flex items-center gap-2 group-hover:gap-4 transition-all uppercase tracking-widest text-white/80">
                      Read More <Arrow />
                    </span>
                  </div>
                </div>
              </Link>
            </motion.div>

            <motion.div variants={fadeUp} className="h-full">
              <Link
                href={SERVICES[1].href}
                className="group block h-full bg-white rounded-2xl p-10 border border-[#e2bebd]/30 hover:shadow-xl hover:shadow-stone-200/60 transition-all duration-300 flex flex-col gap-4 min-h-[360px]"
              >
                <span className="font-body text-xs tracking-[0.3em] uppercase text-[#b31c33] font-bold">{SERVICES[1].num}</span>
                <div className="relative flex-1 rounded-xl overflow-hidden min-h-[160px]">
                  <Image
                    src={SERVICES[1].image!}
                    alt={SERVICES[1].imageAlt!}
                    fill
                    className="object-cover group-hover:scale-105 transition-transform duration-700"
                  />
                </div>
                <div>
                  <h3 className="font-headline text-2xl text-stone-900 mb-2">{SERVICES[1].title}</h3>
                  <p className="text-[#5a4040] text-sm font-body leading-relaxed mb-4">{SERVICES[1].desc}</p>
                  <span className="font-body font-semibold text-xs inline-flex items-center gap-2 group-hover:gap-4 transition-all uppercase tracking-widest text-[#b31c33]/70 group-hover:text-[#b31c33]">
                    Read More <Arrow />
                  </span>
                </div>
              </Link>
            </motion.div>
          </motion.div>

          {/* Row 2: EDR + Vulnerability Management + GRC (3 equal) */}
          <motion.div
            variants={stagger}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-60px" }}
            className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4"
          >
            {[SERVICES[2], SERVICES[3], SERVICES[4]].map((s) => (
              <motion.div key={s.num} variants={fadeUp} className="h-full">
                <Link
                  href={s.href}
                  className="group block h-full bg-white rounded-2xl p-10 border border-[#e2bebd]/30 hover:shadow-lg hover:shadow-stone-200/50 transition-all duration-300 flex flex-col gap-3 min-h-[240px]"
                >
                  <span className="font-body text-xs tracking-[0.3em] uppercase text-[#b31c33] font-bold">{s.num}</span>
                  <h3 className="font-headline text-xl text-stone-900 flex-1">{s.title}</h3>
                  <p className="text-[#5a4040] text-sm font-body leading-relaxed">{s.desc}</p>
                  <span className="font-body font-semibold text-xs inline-flex items-center gap-2 group-hover:gap-4 transition-all uppercase tracking-widest text-[#b31c33]/70 group-hover:text-[#b31c33] mt-2">
                    Read More <Arrow />
                  </span>
                </Link>
              </motion.div>
            ))}
          </motion.div>

          {/* Row 3: PAM (red) + Honeypot (wide image) + Monitoring */}
          <motion.div
            variants={stagger}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-60px" }}
            className="grid grid-cols-1 md:grid-cols-3 gap-4"
          >
            {/* PAM — red card */}
            <motion.div variants={fadeUp} className="h-full">
              <Link
                href={SERVICES[5].href}
                className="group block h-full bg-[#b31c33] rounded-2xl p-10 text-white hover:bg-[#920022] transition-colors duration-300 flex flex-col gap-4 min-h-[280px]"
              >
                <span className="font-body text-xs tracking-[0.3em] uppercase text-white/60 font-bold">{SERVICES[5].num}</span>
                <div className="flex-1 flex flex-col justify-between">
                  <div>
                    <h3 className="font-headline text-2xl text-white mb-3">{SERVICES[5].title}</h3>
                    <p className="text-white/75 text-sm font-body leading-relaxed">{SERVICES[5].desc}</p>
                  </div>
                  <span className="mt-6 font-body font-semibold text-xs inline-flex items-center gap-2 group-hover:gap-4 transition-all uppercase tracking-widest text-white/80">
                    Read More <Arrow />
                  </span>
                </div>
              </Link>
            </motion.div>

            {/* Honeypot — image overlay */}
            <motion.div variants={fadeUp} className="h-full">
              <Link
                href={SERVICES[6].href}
                className="group relative block rounded-2xl overflow-hidden min-h-[280px] h-full"
              >
                <Image
                  src={SERVICES[6].image!}
                  alt={SERVICES[6].imageAlt!}
                  fill
                  className="object-cover group-hover:scale-105 transition-transform duration-700"
                />
                <div className="absolute inset-0 bg-[#1c1b1b]/65 group-hover:bg-[#1c1b1b]/55 transition-colors" />
                <div className="absolute inset-0 p-10 flex flex-col justify-between">
                  <span className="font-body text-xs tracking-[0.3em] uppercase text-white/60 font-bold">{SERVICES[6].num}</span>
                  <div>
                    <h3 className="font-headline text-2xl text-white mb-3">{SERVICES[6].title}</h3>
                    <p className="text-white/70 text-sm font-body leading-relaxed mb-4">{SERVICES[6].desc}</p>
                    <span className="font-body font-semibold text-xs inline-flex items-center gap-2 group-hover:gap-4 transition-all uppercase tracking-widest text-white/80">
                      Read More <Arrow />
                    </span>
                  </div>
                </div>
              </Link>
            </motion.div>

            {/* Monitoring — light card */}
            <motion.div variants={fadeUp} className="h-full">
              <Link
                href={SERVICES[7].href}
                className="group block h-full bg-[#f6f3f2] rounded-2xl p-10 border border-[#e2bebd]/20 hover:bg-white hover:shadow-lg transition-all duration-300 flex flex-col gap-3 min-h-[280px]"
              >
                <span className="font-body text-xs tracking-[0.3em] uppercase text-[#b31c33] font-bold">{SERVICES[7].num}</span>
                <div className="flex-1 flex flex-col justify-between">
                  <div>
                    <h3 className="font-headline text-xl text-stone-900 mb-3">{SERVICES[7].title}</h3>
                    <p className="text-[#5a4040] text-sm font-body leading-relaxed">{SERVICES[7].desc}</p>
                  </div>
                  <span className="mt-6 font-body font-semibold text-xs inline-flex items-center gap-2 group-hover:gap-4 transition-all uppercase tracking-widest text-[#b31c33]/70 group-hover:text-[#b31c33]">
                    Read More <Arrow />
                  </span>
                </div>
              </Link>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* ─── CTA ──────────────────────────────────────────────────────────── */}
      <section className="py-20 bg-[#1c1b1b] px-6 md:px-12">
        <div className="max-w-screen-2xl mx-auto text-center">
          <span className="font-body text-xs tracking-[0.25em] uppercase text-[#ffb3b3] font-bold block mb-6">
            Start Today
          </span>
          <h2 className="font-headline text-3xl sm:text-4xl md:text-5xl text-white mb-6">
            Ready to secure your business?
          </h2>
          <p className="text-stone-400 text-xl max-w-2xl mx-auto mb-10 font-body leading-relaxed">
            Protecting your business from evolving cyber threats requires a partner dedicated to precision and continuous vigilance.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link
              href="/contact#contact-form"
              className="inline-block bg-[#b31c33] text-white px-12 py-4 rounded-xl font-body font-semibold tracking-wide hover:bg-[#920022] shadow-lg shadow-[#b31c33]/30 active:scale-95 transition-all"
            >
              Audit Your Infrastructure
            </Link>
            <Link
              href="/cyber-security"
              className="inline-block border border-white/20 text-white px-12 py-4 rounded-xl font-body font-semibold tracking-wide hover:bg-white/5 transition-colors"
            >
              Cyber Security Services
            </Link>
          </div>
        </div>
      </section>

      <ServicesEcosystem />
    </>
  );
}
