import type { MetadataRoute } from "next";

export const dynamic = "force-static";

const base = "https://illumiasolutions.com";

const routes: { path: string; priority: number; changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"] }[] = [
  { path: "/", priority: 1.0, changeFrequency: "weekly" },
  { path: "/about/", priority: 0.9, changeFrequency: "monthly" },
  { path: "/cloud-services/", priority: 0.9, changeFrequency: "monthly" },
  { path: "/cyber-security/", priority: 0.9, changeFrequency: "monthly" },
  { path: "/open-source-solutions/", priority: 0.9, changeFrequency: "monthly" },
  { path: "/application-solutions/", priority: 0.9, changeFrequency: "monthly" },
  { path: "/case-studies/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/case-studies/pci-dss-grocery/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/case-studies/cybersecurity-open-source/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/case-studies/non-profit-open-source/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/case-studies/proxmox-vmware-migration/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/case-studies/proxmox-hci-expansion/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/case-studies/vmware-proxmox-migration-forceten/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/case-studies/vmware-vsan-proxmox-ceph/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/case-studies/bare-metal-proxmox-migration/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/faqs/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/contact/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/proxmox-migration/", priority: 0.85, changeFrequency: "monthly" },
  { path: "/erpnext/", priority: 0.85, changeFrequency: "monthly" },
  { path: "/odoo/", priority: 0.85, changeFrequency: "monthly" },
  { path: "/netbox/", priority: 0.85, changeFrequency: "monthly" },
  { path: "/ai-governance/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/cybersecurity-solutions/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/cloud-migration-solutions/", priority: 0.8, changeFrequency: "monthly" },
  { path: "/infrastructure-solutions/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/maintenance-services/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/siem-as-a-service/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/siem/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/edr-as-a-service/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/edr-solution/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/pam-as-a-service/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/pam/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/honeypot-as-a-service/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/honeypot-solution/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/soar/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/vulnerability-management/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/governance-risk-compliance/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/application-security/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/mobile-security/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/cloud-security/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/infrastructure-security/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/it-risk-and-security-strategy/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/compliance-services/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/specialized-services/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/waf-as-a-service/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/on-premise-private-cloud/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/object-storage/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/backup-as-a-service/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/disaster-recovery/", priority: 0.75, changeFrequency: "monthly" },
  { path: "/virtual-private-server/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/physical-server/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/containers/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/virtual-desktops/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/software-defined-network/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/monitoring-analytics/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/drive-as-a-service/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/email-as-a-service/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/web-meeting-solution/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/collaborative-editing/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/project-management-solutions/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/nms-as-a-service/", priority: 0.7, changeFrequency: "monthly" },
  { path: "/privacy/", priority: 0.3, changeFrequency: "yearly" },
  { path: "/terms/", priority: 0.3, changeFrequency: "yearly" },
];

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map(({ path, priority, changeFrequency }) => ({
    url: `${base}${path}`,
    changeFrequency,
    priority,
  }));
}
